[package]
name = "{{project_name}}"
version = "0.1.0"
authors = ["{{username}}"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "*"
js_sys = "*"
